export const metadata = { title: 'Terms of Use — Hei Atlas' };

export default function TermsPage() {
  return (
    <main className="min-h-[100dvh] bg-canvas px-4 py-12 safe-x">
      <div className="mx-auto max-w-2xl ds-card p-8 text-ink text-[14px] leading-relaxed">
        <h1 className="text-[22px] font-semibold mb-4">
          Terms of Use: Ambient Clinical Intelligence Platform
        </h1>
        <p className="text-muted mb-6">Last Updated: July 15, 2026</p>

        <p>
          These Terms of Use (&ldquo;Terms&rdquo;) govern your access to and use of the medical
          ambient listening software, applications, APIs, and associated services (collectively,
          the &ldquo;Service&rdquo; or &ldquo;Platform&rdquo;) provided by Oncology Solutions LLC
          (&ldquo;Company,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;).
        </p>
        <p className="mt-4">
          By registering for an account, accessing, or using the Platform, you
          (&ldquo;User,&rdquo; &ldquo;Clinician,&rdquo; or &ldquo;You&rdquo;) agree to be bound by
          these Terms. If you are entering into these Terms on behalf of a clinic, hospital
          system, or other legal entity (an &ldquo;Enterprise Customer&rdquo;), you represent that
          you have the authority to bind such entity to these Terms.
        </p>

        <h2 className="text-[16px] font-semibold mt-8 mb-2">
          1. Clinical Disclaimer &amp; User Responsibility
        </h2>
        <p className="font-medium mt-3">1.1 Draft Tool Only</p>
        <p>
          The Platform is an assistive administrative tool powered by artificial intelligence and
          machine learning designed to draft clinical notes, summaries, and structured medical
          documentation (e.g., SOAP notes) based on ambient audio captured during clinical
          encounters. The Platform does not practice medicine, provide medical advice, or render
          diagnoses.
        </p>
        <p className="font-medium mt-4">1.2 &ldquo;Human-in-the-Loop&rdquo; Mandatory Review</p>
        <ul className="list-disc pl-5 mt-2 space-y-2">
          <li>
            <span className="font-medium">Clinician Responsibility:</span> You retain sole and
            absolute clinical, ethical, and legal responsibility for all patient care, diagnoses,
            treatment decisions, and the accuracy of the medical record.
          </li>
          <li>
            <span className="font-medium">Mandatory Review &amp; Audit:</span> You are strictly
            required to thoroughly review, edit, and correct any draft note, summary, or clinical
            documentation generated by the Platform before finalizing, signing, or exporting it to
            an Electronic Health Record (EHR) system.
          </li>
          <li>
            <span className="font-medium">No Reliance on AI Inaccuracies:</span> Generative AI
            models are subject to errors, omissions, or misinterpretations (collectively,
            &ldquo;hallucinations&rdquo;). The Company is not liable for any clinical errors,
            medical malpractice claims, or adverse patient outcomes resulting from finalized notes
            that you failed to properly review and edit.
          </li>
        </ul>

        <h2 className="text-[16px] font-semibold mt-8 mb-2">
          2. Patient Consent, Privacy &amp; Legal Compliance
        </h2>
        <p className="font-medium mt-3">2.1 Wiretapping &amp; Recording Laws</p>
        <p>
          Ambient listening technology relies on capturing live verbal exchanges in clinical exam
          rooms or telehealth environments.
        </p>
        <ul className="list-disc pl-5 mt-2 space-y-2">
          <li>
            <span className="font-medium">Two-Party/All-Party Consent Jurisdictions:</span> Several
            U.S. states require the explicit consent of all parties to a conversation before it can
            be recorded or transcribed.
          </li>
          <li>
            <span className="font-medium">Your Absolute Duty:</span> You are solely responsible for
            knowing the recording laws of your jurisdiction. You covenant and warrant that you will
            obtain all necessary, legally compliant verbal or written consents from patients,
            family members, and any other individuals present in the room before activating the
            Platform&rsquo;s ambient recording features for any encounter.
          </li>
        </ul>
        <p className="font-medium mt-4">2.2 Patient Refusal and Opt-Out</p>
        <p>
          If a patient declines, objects, or withdraws consent to have their encounter processed by
          an ambient AI tool, you must immediately deactivate or refrain from starting the
          Platform&rsquo;s recording session. You agree that a patient&rsquo;s refusal to be
          recorded will not negatively impact their access to care.
        </p>
        <p className="font-medium mt-4">2.3 HIPAA and Protected Health Information (PHI)</p>
        <p>
          Both parties acknowledge that the use of the Platform involves the processing of
          Protected Health Information (PHI) under the Health Insurance Portability and
          Accountability Act (HIPAA).
        </p>
        <ul className="list-disc pl-5 mt-2 space-y-2">
          <li>
            <span className="font-medium">Business Associate Agreement (BAA):</span> Your use of
            the Platform is strictly conditioned upon the execution of a mutually acceptable HIPAA
            Business Associate Agreement (BAA) between the Company and you or your Enterprise
            Customer. If no BAA is in place, you are prohibited from transmitting PHI to the
            Platform.
          </li>
        </ul>

        <h2 className="text-[16px] font-semibold mt-8 mb-2">
          3. Account Eligibility &amp; NPI Verification
        </h2>
        <ul className="list-disc pl-5 mt-2 space-y-2">
          <li>
            <span className="font-medium">Credential Verification:</span> Access to this Platform
            is restricted strictly to licensed healthcare professionals (e.g., MDs, DOs, NPs, PAs,
            RNs) practicing within the United States. To register, you must provide a valid
            National Provider Identifier (NPI) and medical credentials.
          </li>
          <li>
            <span className="font-medium">Prohibition on Falsification:</span> Falsifying medical
            credentials, utilizing another provider&rsquo;s NPI, or permitting unlicensed
            individuals to utilize your clinical seat will result in immediate termination of your
            account and referral to appropriate regulatory authorities.
          </li>
          <li>
            <span className="font-medium">Security of Credentials:</span> You are responsible for
            safeguarding your login credentials. You must immediately notify us of any unauthorized
            use of your account.
          </li>
        </ul>

        <h2 className="text-[16px] font-semibold mt-8 mb-2">
          4. Data Processing, Retention &amp; Transient Storage
        </h2>
        <p>
          To protect patient privacy, minimize data surfaces, and limit security liabilities, the
          Platform operates under a strict data minimization protocol:
        </p>
        <ul className="list-disc pl-5 mt-2 space-y-2">
          <li>
            <span className="font-medium">Audio Deletion:</span> Once ambient audio is successfully
            captured, transcribed, and processed into a draft clinical note, the raw audio file is
            immediately and permanently deleted from our active servers, unless otherwise
            explicitly configured by your Enterprise agreement.
          </li>
          <li>
            <span className="font-medium">No External Training on Patient PHI:</span> The Company
            does not use Patient PHI or raw audio data to train public, third-party generative AI
            models.
          </li>
          <li>
            <span className="font-medium">Product Improvement Data:</span> We may use fully
            de-identified, aggregated clinical data (stripped of all 18 HIPAA identifiers) to
            refine, benchmark, and improve our machine learning algorithms in compliance with HIPAA
            de-identification standards.
          </li>
        </ul>

        <h2 className="text-[16px] font-semibold mt-8 mb-2">5. Prohibited Uses</h2>
        <p>You agree not to, and will not permit any third party to:</p>
        <ol className="list-decimal pl-5 mt-2 space-y-2">
          <li>Use the Platform for any consumer-facing self-diagnosis tool or to bypass professional human clinical judgment.</li>
          <li>Record encounters without active verbal or written patient consent.</li>
          <li>Reverse engineer, decompile, or attempt to extract the source code or underlying algorithms of the Platform.</li>
          <li>Input into the Platform any voice files or documents for which you do not possess the requisite copyrights or processing permissions.</li>
          <li>Bypass, disable, or circumvent any security measures, access controls, or rate-limiting protocols built into the Platform.</li>
        </ol>

        <h2 className="text-[16px] font-semibold mt-8 mb-2">6. Intellectual Property &amp; Feedback</h2>
        <ul className="list-disc pl-5 mt-2 space-y-2">
          <li>
            <span className="font-medium">Our Ownership:</span> The Company retains all right,
            title, and interest in and to the Platform, including all AI engines, custom language
            models, natural language processing pipelines, software updates, and user interfaces.
          </li>
          <li>
            <span className="font-medium">Feedback:</span> If you provide any suggestions, feature
            requests, or performance feedback regarding the Platform, you grant the Company an
            unrestricted, perpetual, royalty-free license to use and incorporate such feedback to
            improve our services without obligation to you.
          </li>
        </ul>

        <h2 className="text-[16px] font-semibold mt-8 mb-2">7. Disclaimer of Warranties</h2>
        <p className="uppercase text-[13px]">
          The Platform is provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis.
          To the maximum extent permitted by law, the Company disclaims all warranties, whether
          express, implied, or statutory, including but not limited to warranties of
          merchantability, fitness for a particular purpose, non-infringement, and system accuracy.
        </p>
        <p className="uppercase text-[13px] mt-3">
          We do not warrant that the transcribed texts or generated clinical notes will be 100%
          error-free, complete, secure, or uninterrupted. Genetic factors, co-morbidities, drug
          interactions, and other relevant symptom pathways drafted by the Platform must always be
          verified independently by clinical standards.
        </p>

        <h2 className="text-[16px] font-semibold mt-8 mb-2">8. Limitation of Liability</h2>
        <p className="uppercase text-[13px]">
          To the maximum extent permitted by law, in no event shall the Company, its affiliates, or
          its officers be liable for any consequential, indirect, incidental, special, punitive, or
          exemplary damages, or for any damages resulting from medical malpractice, clinical
          errors, inaccurate EHR documentation, lost revenues, or loss of data, even if
          foreseeable.
        </p>
        <p className="uppercase text-[13px] mt-3">
          The Company&rsquo;s total aggregate liability arising out of or in connection with these
          Terms or your use of the Platform shall not exceed the total fees paid by you (or your
          Enterprise Customer) to the Company in the twelve (12) months preceding the event giving
          rise to liability.
        </p>

        <h2 className="text-[16px] font-semibold mt-8 mb-2">9. Indemnification</h2>
        <p>
          You agree to indemnify, defend, and hold harmless the Company, its directors, and
          employees from and against any third-party claims, damages, liabilities, costs, and
          expenses (including reasonable attorneys&rsquo; fees) arising out of or related to:
        </p>
        <ol className="list-decimal pl-5 mt-2 space-y-2">
          <li>Your clinical practice, medical decisions, or patient treatment outcomes.</li>
          <li>Your failure to obtain necessary, legally compliant patient consents prior to recording clinical encounters.</li>
          <li>Your breach of any representation, warranty, or covenant contained within these Terms or the executed BAA.</li>
        </ol>

        <h2 className="text-[16px] font-semibold mt-8 mb-2">10. Governing Law &amp; Arbitration</h2>
        <ul className="list-disc pl-5 mt-2 space-y-2">
          <li>
            <span className="font-medium">Governing Law:</span> These Terms shall be governed by
            and construed in accordance with the laws of the State of Indiana, without regard to
            conflict of law principles.
          </li>
          <li>
            <span className="font-medium">Dispute Resolution:</span> Any dispute, claim, or
            controversy arising out of or relating to these Terms shall be resolved through
            binding, confidential arbitration administered by JAMS in Indianapolis, Indiana, and
            judgment on the award rendered by the arbitrator(s) may be entered in any court having
            jurisdiction thereof.
          </li>
        </ul>

        <h2 className="text-[16px] font-semibold mt-8 mb-2">11. Modifications to Terms</h2>
        <p>
          We reserve the right to modify these Terms at any time. We will provide notice of
          material updates by posting the updated Terms on our website and updating the
          &ldquo;Last Updated&rdquo; date, or by sending you an email notification. Your continued
          use of the Platform after such modifications constitutes your acceptance of the revised
          Terms.
        </p>

        <h2 className="text-[16px] font-semibold mt-8 mb-2">12. Contact Information</h2>
        <p>
          For questions, notices, or support inquiries regarding these Terms, please contact us at{' '}
          <a className="text-accent" href="mailto:compliance@oncologysolutions.us">
            compliance@oncologysolutions.us
          </a>
          .
        </p>
      </div>
    </main>
  );
}
