export const metadata = { title: 'Terms of Service — Hei Atlas' };

export default function TermsPage() {
  return (
    <main className="min-h-[100dvh] bg-canvas px-4 py-12 safe-x">
      <div className="mx-auto max-w-2xl ds-card p-8 text-ink text-[14px] leading-relaxed">
        <h1 className="text-[22px] font-semibold mb-4">Terms of Service</h1>
        <p className="text-muted mb-6">Last updated: July 3, 2026</p>

        <h2 className="text-[16px] font-semibold mt-6 mb-2">1. Beta software</h2>
        <p>
          Hei Atlas is beta software provided to licensed clinicians for evaluation. It is not
          a substitute for clinical judgment. Notes generated by the service must be reviewed
          and signed by the treating physician before entering the medical record.
        </p>

        <h2 className="text-[16px] font-semibold mt-6 mb-2">2. Eligibility</h2>
        <p>
          By creating an account you represent that you are a licensed healthcare professional
          in good standing and that the NPI you supply is your own.
        </p>

        <h2 className="text-[16px] font-semibold mt-6 mb-2">3. Protected Health Information</h2>
        <p>
          Encounter data is retained for 24 hours in production infrastructure covered by a
          Business Associate Agreement with our LLM vendors, then hard-deleted. Do not include
          direct patient identifiers (name, MRN, DOB) in transcripts; use initials or a private
          reference known only to you.
        </p>

        <h2 className="text-[16px] font-semibold mt-6 mb-2">4. No warranty</h2>
        <p>
          The service is provided &ldquo;as is&rdquo; without warranty of any kind. Clinical decisions
          are the sole responsibility of the treating physician.
        </p>

        <h2 className="text-[16px] font-semibold mt-6 mb-2">5. Contact</h2>
        <p>
          Questions: <a className="text-accent" href="mailto:support@heiatlas.ai">support@heiatlas.ai</a>
        </p>

        <p className="mt-8 text-muted text-[12px]">
          This is a placeholder for beta launch. Consult qualified counsel before opening
          general availability.
        </p>
      </div>
    </main>
  );
}
